sudo: false
language: node_js
node_js:
- "node"
- 12
- 11
- 10
- 9
- 8
- 7
- 6
- "lts/*"
before_install:
- npm install -g grunt-cli
install:
- npm install
script:
- make audit
- make tests
- make validate
